apiVersion: v1
kind: Service
metadata:
   name: mongo-back-service
spec:
   selector:
      type: mongo-backend
   type: ClusterIP
   ports:
   -  port: 27017
      targetPort: 27017

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo-back-deployment
spec:
  selector:
    matchLabels:
      type: mongo-backend
  template:
    metadata:
      labels:
        type: mongo-backend
    spec:
      containers:
      - name: mongo-back-container
        image: mongo
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 27017
